run make manifest-local
Signed-off-by: Mangaal <angommeeteimangaal@gmail.com>

diff --git a/manifests/ha/namespace-install-with-hydrator.yaml b/manifests/ha/namespace-install-with-hydrator.yaml
--- a/manifests/ha/namespace-install-with-hydrator.yaml
+++ b/manifests/ha/namespace-install-with-hydrator.yaml
@@ -623,6 +623,29 @@ data:
     ROLE=''
     REDIS_MASTER=''
 
+    # Load AUTH from file or env
+    echo "Loading redis credentials"
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
+      file_auth="$(< "${REDIS_CREDS_FILE_PATH}/auth" tr -d '\n\r')"
+      if [ -n "$file_auth" ]; then
+        echo "Retrieved Redis credentials from file."
+        AUTH="$file_auth"
+      elif [ -n "${AUTH:-}" ]; then
+        echo "Retrieved Redis password from environment (file was empty)."
+      else
+        echo "ERROR: Redis credential file is empty and no environment variable set."
+        exit 1
+      fi
+
+    elif [ -n "${AUTH:-}" ]; then
+      # No valid file, but env var is set
+      echo "Retrieved Redis password from environment."
+    else
+      # Neither source provided anything
+      echo "WARNING: Redis password not set via file or environment."
+      exit 1
+    fi
+
     set -eu
     sentinel_get_master() {
     set +e
@@ -931,6 +954,34 @@ data:
   haproxy_init.sh: |
     HAPROXY_CONF=/data/haproxy.cfg
     cp /readonly/haproxy.cfg "$HAPROXY_CONF"
+
+    # Load AUTH from file or env
+    echo "Loading redis credentials"
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
+      file_auth="$(< "${REDIS_CREDS_FILE_PATH}/auth" tr -d '\n\r')"
+      if [ -n "$file_auth" ]; then
+        echo "Retrieved Redis credentials from file."
+        AUTH="$file_auth"
+      elif [ -n "${AUTH:-}" ]; then
+        echo "Retrieved Redis password from environment (file was empty)."
+      else
+        echo "ERROR: Redis credential file is empty and no environment variable set."
+        exit 1
+      fi
+
+    elif [ -n "${AUTH:-}" ]; then
+      # No valid file, but env var is set
+      echo "Retrieved Redis password from environment."
+    else
+      # Neither source provided anything
+      echo "WARNING: Redis password not set via file or environment."
+      exit 1
+    fi
+
+    # Inject AUTH into haproxy config
+    ESCAPED_AUTH=$(echo "$AUTH" | sed -e 's/[\/&]/\\&/g')
+    sed -i "s|\${AUTH}|${ESCAPED_AUTH}|" "$HAPROXY_CONF"
+
     for loop in $(seq 1 10); do
       getent hosts argocd-redis-ha-announce-0 && break
       echo "Waiting for service argocd-redis-ha-announce-0 to be ready ($loop) ..." && sleep 1
@@ -978,6 +1029,47 @@ data:
     SERVICE=argocd-redis-ha
     SENTINEL_TLS_REPLICATION_ENABLED=false
     REDIS_TLS_REPLICATION_ENABLED=false
+
+    load_auth_password() {
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
+        REDIS_PASSWORD_FILE="${REDIS_CREDS_FILE_PATH}/auth"
+        file_auth="$(< "$REDIS_PASSWORD_FILE" tr -d '\r\n')"
+        if [ -n "$file_auth" ]; then
+            echo "Retrieved Redis credentials from file"
+            AUTH="$file_auth"
+            return 0
+        else
+            echo "WARNING: Redis credential file is empty"
+            # fall through to try env
+        fi
+    fi
+    if [ -n "${AUTH:-}" ]; then
+        echo "Retrieved Redis credentials from environment"
+    else
+        echo "ERROR: Redis credentials not set via file or environment"
+        exit 1
+    fi
+    }
+
+    load_sentinel_password() {
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/sentinel_auth" ]; then
+        SENTINEL_PASSWORD_FILE="${REDIS_CREDS_FILE_PATH}/sentinel_auth"
+        file_auth="$(< "$SENTINEL_PASSWORD_FILE" tr -d '\n\r')"
+        if [ -n "$file_auth" ]; then
+            echo "Retrieved Redis sentinel credentials from file"
+            SENTINELAUTH="$file_auth"
+            return 0
+        else
+            echo "WARNING: Redis sentinel credential file is empty"
+            # fall through to try env
+        fi
+    fi
+    if [ -n "${SENTINELAUTH:-}" ]; then
+        echo "Retrieved Redis sentinel credentials from environment"
+    else
+        echo "WARNING: Redis sentinel credentials not set via file or environment."
+    fi
+    }
 
     set -eu
     sentinel_get_master() {
@@ -1199,6 +1291,11 @@ data:
 
     identify_announce_ip
 
+    # Load Redis credentials from file or env
+    echo "Loading redis credentials"
+    load_auth_password
+    load_sentinel_password
+
     if [ -z "${ANNOUNCE_IP}" ]; then
         "Error: Could not resolve the announce ip for this pod"
         exit 1
@@ -1246,7 +1343,30 @@ data:
         maxclients 10000
         sentinel parallel-syncs argocd 5
     sentinel auth-pass argocd replace-default-auth
-  trigger-failover-if-master.sh: |
+  trigger-failover-if-master.sh: |-
+    # Load AUTH from file or env
+    echo "Loading redis credentials"
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
+      file_auth="$(< "${REDIS_CREDS_FILE_PATH}/auth" tr -d '\n\r')"
+      if [ -n "$file_auth" ]; then
+        echo "Retrieved Redis credentials from file."
+        AUTH="$file_auth"
+      elif [ -n "${AUTH:-}" ]; then
+        echo "Retrieved Redis password from environment (file was empty)."
+      else
+        echo "ERROR: Redis credential file is empty and no environment variable set."
+        exit 1
+      fi
+
+    elif [ -n "${AUTH:-}" ]; then
+      # No valid file, but env var is set
+      echo "Retrieved Redis password from environment."
+    else
+      # Neither source provided anything
+      echo "WARNING: Redis password not set via file or environment."
+      exit 1
+    fi
+
     get_redis_role() {
       is_master=$(
         redis-cli \
@@ -1288,6 +1408,29 @@ metadata:
 apiVersion: v1
 data:
   redis_liveness.sh: |
+    # Load AUTH from file or env
+    echo "Loading redis credentials"
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
+      file_auth="$(< "${REDIS_CREDS_FILE_PATH}/auth" tr -d '\n\r')"
+      if [ -n "$file_auth" ]; then
+        echo "Retrieved Redis credentials from file."
+        AUTH="$file_auth"
+      elif [ -n "${AUTH:-}" ]; then
+        echo "Retrieved Redis password from environment (file was empty)."
+      else
+        echo "ERROR: Redis credential file is empty and no environment variable set."
+        exit 1
+      fi
+
+    elif [ -n "${AUTH:-}" ]; then
+      # No valid file, but env var is set
+      echo "Retrieved Redis password from environment."
+    else
+      # Neither source provided anything
+      echo "WARNING: Redis password not set via file or environment."
+      exit 1
+    fi
+
     response=$(
       redis-cli \
         -a "${AUTH}" --no-auth-warning \
@@ -1301,7 +1444,30 @@ data:
       *) exit 1 ;;
     esac
     exit 0
-  redis_readiness.sh: |
+  redis_readiness.sh: |-
+    # Load AUTH from file or env
+    echo "Loading redis credentials"
+    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
+      file_auth="$(< "${REDIS_CREDS_FILE_PATH}/auth" tr -d '\n\r')"
+      if [ -n "$file_auth" ]; then
+        echo "Retrieved Redis credentials from file."
+        AUTH="$file_auth"
+      elif [ -n "${AUTH:-}" ]; then
+        echo "Retrieved Redis password from environment (file was empty)."
+      else
+        echo "ERROR: Redis credential file is empty and no environment variable set."
+        exit 1
+      fi
+
+    elif [ -n "${AUTH:-}" ]; then
+      # No valid file, but env var is set
+      echo "Retrieved Redis password from environment."
+    else
+      # Neither source provided anything
+      echo "WARNING: Redis password not set via file or environment."
+      exit 1
+    fi
+
     response=$(
       redis-cli \
         -a "${AUTH}" --no-auth-warning \
@@ -2361,6 +2527,33 @@ spec:
         - mountPath: /run/haproxy
           name: shared-socket
       initContainers:
+      - args:
+        - /readonly/haproxy_init.sh
+        command:
+        - sh
+        env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /redis-creds
+        image: public.ecr.aws/docker/library/haproxy:3.0.8-alpine
+        imagePullPolicy: IfNotPresent
+        name: config-init
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+            - ALL
+          readOnlyRootFilesystem: true
+          seccompProfile:
+            type: RuntimeDefault
+        volumeMounts:
+        - mountPath: /redis-creds
+          name: redis-creds
+          readOnly: true
+        - mountPath: /readonly
+          name: config-volume
+          readOnly: true
+        - mountPath: /data
+          name: data
       - command:
         - argocd
         - admin
@@ -2377,33 +2570,19 @@ spec:
           runAsNonRoot: true
           seccompProfile:
             type: RuntimeDefault
-      - args:
-        - /readonly/haproxy_init.sh
-        command:
-        - sh
-        image: public.ecr.aws/docker/library/haproxy:3.0.8-alpine
-        imagePullPolicy: IfNotPresent
-        name: config-init
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-            - ALL
-          readOnlyRootFilesystem: true
-          seccompProfile:
-            type: RuntimeDefault
-        volumeMounts:
-        - mountPath: /readonly
-          name: config-volume
-          readOnly: true
-        - mountPath: /data
-          name: data
       securityContext:
         fsGroup: 99
         runAsNonRoot: true
         runAsUser: 99
       serviceAccountName: argocd-redis-ha-haproxy
       volumes:
+      - name: redis-creds
+        secret:
+          items:
+          - key: auth
+            path: auth
+          optional: true
+          secretName: argocd-redis
       - configMap:
           name: argocd-redis-ha-configmap
         name: config-volume
@@ -2449,6 +2628,8 @@ spec:
       - args:
         - /usr/local/bin/argocd-repo-server
         env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: REDIS_PASSWORD
           valueFrom:
             secretKeyRef:
@@ -2694,6 +2875,9 @@ spec:
           seccompProfile:
             type: RuntimeDefault
         volumeMounts:
+        - mountPath: /run/secrets/argocd/redis-auth
+          name: redis-creds
+          readOnly: true
         - mountPath: /app/config/ssh
           name: ssh-known-hosts
         - mountPath: /app/config/tls
@@ -2734,6 +2918,13 @@ spec:
         kubernetes.io/os: linux
       serviceAccountName: argocd-repo-server
       volumes:
+      - name: redis-creds
+        secret:
+          items:
+          - key: auth
+            path: auth
+          optional: true
+          secretName: argocd-redis
       - configMap:
           name: argocd-ssh-known-hosts-cm
         name: ssh-known-hosts
@@ -2803,6 +2994,8 @@ spec:
         env:
         - name: ARGOCD_API_SERVER_REPLICAS
           value: "2"
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: REDIS_PASSWORD
           valueFrom:
             secretKeyRef:
@@ -3119,6 +3312,9 @@ spec:
           seccompProfile:
             type: RuntimeDefault
         volumeMounts:
+        - mountPath: /run/secrets/argocd/redis-auth
+          name: redis-creds
+          readOnly: true
         - mountPath: /app/config/ssh
           name: ssh-known-hosts
         - mountPath: /app/config/tls
@@ -3137,6 +3333,13 @@ spec:
         kubernetes.io/os: linux
       serviceAccountName: argocd-server
       volumes:
+      - name: redis-creds
+        secret:
+          items:
+          - key: auth
+            path: auth
+          optional: true
+          secretName: argocd-redis
       - emptyDir: {}
         name: plugins-home
       - emptyDir: {}
@@ -3213,6 +3416,8 @@ spec:
       - args:
         - /usr/local/bin/argocd-application-controller
         env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: REDIS_PASSWORD
           valueFrom:
             secretKeyRef:
@@ -3497,6 +3702,9 @@ spec:
           name: argocd-cmd-params-cm
         - mountPath: /tmp
           name: argocd-application-controller-tmp
+        - mountPath: /run/secrets/argocd/redis-auth
+          name: redis-creds
+          readOnly: true
         workingDir: /home/argocd
       nodeSelector:
         kubernetes.io/os: linux
@@ -3524,6 +3732,13 @@ spec:
           name: argocd-cmd-params-cm
           optional: true
         name: argocd-cmd-params-cm
+      - name: redis-creds
+        secret:
+          items:
+          - key: auth
+            path: auth
+          optional: true
+          secretName: argocd-redis
 ---
 apiVersion: apps/v1
 kind: StatefulSet
@@ -3561,6 +3776,8 @@ spec:
         command:
         - redis-server
         env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: AUTH
           valueFrom:
             secretKeyRef:
@@ -3620,6 +3837,9 @@ spec:
           successThreshold: 1
           timeoutSeconds: 15
         volumeMounts:
+        - mountPath: /run/secrets/argocd/redis-auth
+          name: redis-creds
+          readOnly: true
         - mountPath: /readonly-config
           name: config
           readOnly: true
@@ -3632,6 +3852,8 @@ spec:
         command:
         - redis-sentinel
         env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: AUTH
           valueFrom:
             secretKeyRef:
@@ -3701,6 +3923,8 @@ spec:
         command:
         - sh
         env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: SENTINEL_ID_0
           value: 3c0d9c0320bb34888c2df5757c718ce6ca992ce6
         - name: SENTINEL_ID_1
@@ -3725,6 +3949,9 @@ spec:
           seccompProfile:
             type: RuntimeDefault
         volumeMounts:
+        - mountPath: /run/secrets/argocd/redis-auth
+          name: redis-creds
+          readOnly: true
         - mountPath: /readonly-config
           name: config
           readOnly: true
@@ -3736,6 +3963,8 @@ spec:
         command:
         - sh
         env:
+        - name: REDIS_CREDS_FILE_PATH
+          value: /run/secrets/argocd/redis-auth
         - name: SENTINEL_ID_0
           value: 3c0d9c0320bb34888c2df5757c718ce6ca992ce6
         - name: SENTINEL_ID_1
@@ -3759,6 +3988,9 @@ spec:
           seccompProfile:
             type: RuntimeDefault
         volumeMounts:
+        - mountPath: /run/secrets/argocd/redis-auth
+          name: redis-creds
+          readOnly: true
         - mountPath: /readonly-config
           name: config
           readOnly: true
@@ -3771,6 +4003,13 @@ spec:
       serviceAccountName: argocd-redis-ha
       terminationGracePeriodSeconds: 60
       volumes:
+      - name: redis-creds
+        secret:
+          items:
+          - key: auth
+            path: auth
+          optional: false
+          secretName: argocd-redis
       - configMap:
           name: argocd-redis-ha-configmap
         name: config
